### PR TITLE
User login

### PR DESCRIPTION
**Pull request by kili236**
[Recap of our workflow](https://github.com/softozor/shopozor-backend#pull-requests)

# Prerequisites

- [ ] You have configured the triggering of the pre-commit hook on your local repository's clone. You need to have installed the python module `pre-commit` (listed in [the required dev modules](requirements-dev.txt)) and run the command `pre-commit install` in the repository's root folder.
- [ ] You have covered your code with unit and acceptance tests
- [ ] The feature you have implemented has no tag `@wip` any more
- [ ] None of the feature files have a tag `@current` or `@focus`

# Changes

The Login class has been moved into the mutations.py file.
In addition, if the user enters an empty password, the WRONG_CREDENTIALS error message is returned

# How to use the feature

Same as previously

# Additional notes

### CODE REVIEW

**Comment by zadigus** [comment]
ok to test

**Comment by softozor-deployer** [comment]
Can one of the admins verify this patch?

**Comment by softozor-deployer** [comment]
Can one of the admins verify this patch?

**Comment by zadigus** [comment]
First time we have all the tests passing!!!! wooohooooo!

**Pull request merged**
